# Generated by Django 5.2.4 on 2025-08-09 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(blank=True, max_length=200)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.alumno')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.profesor')),
            ],
        ),
    ]
