# Generated by Django 5.2.4 on 2025-08-11 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en euros', max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='pago',
            name='importe',
        ),
        migrations.AddField(
            model_name='pago',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado en euros', max_digits=5),
        ),
        migrations.AddField(
            model_name='pago',
            name='importe_final',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Importe final después del descuento', max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='importe_original',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Importe original de la tarifa', max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.tarifa'),
        ),
    ]
