# Generated by Django 5.2.4 on 2025-08-11 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_tarifa_remove_pago_importe_pago_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='tarifa_predeterminada',
            field=models.ForeignKey(blank=True, help_text='Tarifa predeterminada para este alumno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.tarifa'),
        ),
    ]
