# Generated by Django 5.2.4 on 2025-08-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alumno_tarifa_predeterminada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Descripción del gasto', max_length=200)),
                ('importe', models.DecimalField(decimal_places=2, help_text='Importe en euros', max_digits=10)),
                ('categoria', models.CharField(choices=[('suministros', 'Suministros'), ('inmobiliario', 'Inmobiliario'), ('equipamiento', 'Equipamiento'), ('limpieza', 'Limpieza'), ('marketing', 'Marketing'), ('administrativo', 'Administrativo'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_gasto', models.DateField(help_text='Fecha en que se realizó el gasto')),
                ('comprobante', models.FileField(blank=True, help_text='Factura o comprobante del gasto', null=True, upload_to='gastos/')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha_gasto', '-fecha'],
            },
        ),
    ]
