# Generated by Django 5.2.4 on 2025-08-11 20:44

import django.core.validators
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_gasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='comprobante',
        ),
        migrations.AddField(
            model_name='gasto',
            name='factura',
            field=models.FileField(blank=True, help_text='Factura o comprobante del gasto (PDF, JPG, PNG)', null=True, upload_to=gestion.models.gasto_factura_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Solo se permiten archivos PDF, JPG o PNG.')]),
        ),
    ]
