# Generated by Django 5.2.4 on 2025-08-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_remove_gasto_comprobante_gasto_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='es_compartido',
            field=models.BooleanField(default=False, help_text='Indica si este alumno puede ser compartido entre profesores en el mismo horario'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(blank=True, help_text='DNI del alumno (opcional)', max_length=20, null=True, unique=True),
        ),
    ]
