# Generated by Django 5.2.4 on 2025-08-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alumno_es_compartido_alter_alumno_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.CharField(blank=True, choices=[('1P', '1º Primaria'), ('2P', '2º Primaria'), ('3P', '3º Primaria'), ('4P', '4º Primaria'), ('5P', '5º Primaria'), ('6P', '6º Primaria'), ('1E', '1º E.S.O'), ('2E', '2º E.S.O'), ('3E', '3º E.S.O'), ('4E', '4º E.S.O'), ('1B', '1º Bachillerato'), ('2B', '2º Bachillerato'), ('FP', 'FP'), ('AD', 'Adultos'), ('EB', 'EBAU'), ('EO', 'EOI')], help_text='Curso en el que está matriculado el alumno', max_length=2),
        ),
    ]
